---

- name: "Common | Dirs | Create"
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: "{{ item.state | default('directory') }}"
    owner: "{{ item.owner | default('') }}"
    group: "{{ item.group | default('') }}"
    mode: "{{ item.mode | default('755') }}"
    force: "{{ item.force | default(false) }}"
    follow: "{{ item.follow | default(true) }}"
  become: true
  with_items: "{{ common_dirs }}"
  tags:
    - common
    - common-dirs
