# code: language=ansible
---

- name: "Common | Hostname | Set hostname"
  ansible.builtin.hostname:
    name: "{{ common_hostname }}"
  become: yes
  become_user: "{{ ansible_become_user }}"
  tags:
    - common
    - common-hostname
