---
dependency:
  name: galaxy

driver:
  name: docker

scenario:
  name: "docker-jammy"

platforms:
  # Ubuntu 22.04 (Jammy)
  - name: "ubuntu-jammy"
    image: "reg.sys.im/tools-molecule-systemd:jammy"
    privileged: true
    pre_build_image: true
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    security_opt:
      - seccomp=unconfined
    capabilities:
      - CAP_SYS_ADMIN
    override_command: false
    cgroupns: private
    cgroup_parent: "docker.slice"
    groups:
      - ubuntu
      - deb

provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: true
  options:
    vvv: true
  inventory:
    links:
      host_vars: ../.inventory/host_vars
      group_vars: ../.inventory/group_vars

verifier:
  name: ansible
