# code: language=ansible
---

- name: "Common | Auditd | Install | Apt"
  ansible.builtin.apt:
    name: "{{ common_auditd_packages }}"
    state: present
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
  become: yes
  tags:
    - common
    - common-auditd
    - common-auditd-install
