# code: language=ansible
---

- name: "Common | Auditd | Install | Dnf"
  ansible.builtin.dnf:
    name: "{{ common_auditd_packages }}"
    state: present
    update_cache: no
  become: yes
  become_user: "{{ ansible_become_user }}"
  tags:
    - common
    - common-auditd
    - common-auditd-install
