# code: language=ansible
---

- name: "Common | Atop | Install | Apt"
  ansible.builtin.apt:
    name: "{{ common_atop_packages }}"
    state: present
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
  become: yes
  tags:
    - common
    - common-atop
    - common-atop-install
