# code: language=ansible
---

- name: "Common | Atop | Install | Dnf"
  ansible.builtin.dnf:
    name: "{{ common_atop_packages }}"
    state: present
    update_cache: false
  become: true
  tags:
    - common
    - common-atop
    - common-atop-install
