# code: language=ansible
---

- name: "Common | Timezone | Configure"
  community.general.timezone:
    name: "{{ common_timezone }}"
  become: yes
  become_user: "{{ ansible_become_user }}"
  tags:
    - common
    - common-timezone
