# code: language=ansible
---

- name: "Common | Firewall | IPTables | Install"
  ansible.builtin.include_tasks: "firewall/iptables/install/{{ dist_pkg_mgr }}.yml"
  tags:
    - common
    - common-firewall
    - common-firewall-install

- name: "Common | Firewall | IPTables | IPSet Configure"
  ansible.builtin.template:
    src: "firewall/iptables/ipset.j2"
    dest: "{{ common_firewall_ipset_config }}"
    owner: "root"
    group: "root"
    mode: "0600"
    backup: no
  notify:
    - Restart ipset
  become: yes
  tags:
    - common
    - common-firewall
    - common-firewall-configure

- name: "Common | Firewall | IPTables | IPSet Restart Script"
  ansible.builtin.template:
    src: "firewall/iptables/ipset-restart.sh.j2"
    dest: "/usr/local/bin/ipset-restart.sh"
    owner: "root"
    group: "root"
    mode: "0700"
    backup: no
  become: yes
  tags:
    - common
    - common-firewall
    - common-firewall-configure

- name: "Common | Firewall | IPTables | Enable ipset service"
  ansible.builtin.service:
    name: "{{ common_firewall_ipset_service }}"
    enabled: yes
    state: started
  become: yes
  tags:
    - common
    - common-firewall
    - common-firewall-service

- name: "Common | Firewall | IPTables | IPSet flush handlers"
  ansible.builtin.meta: flush_handlers
  tags:
    - common
    - common-firewall
    - common-firewall-service

- name: "Common | Firewall | IPTables | Configure"
  ansible.builtin.template:
    src: "firewall/iptables/iptables.j2"
    dest: "{{ common_firewall_iptables_config }}"
    owner: "root"
    group: "root"
    mode: "0600"
    backup: no
  notify:
    - Restart iptables
    - Restart docker
    - Restart kube-proxy
  become: yes
  tags:
    - common
    - common-firewall
    - common-firewall-configure

- name: "Common | Firewall | IPTables | Disable firewalld / ufw services"
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: no
    state: stopped
  with_items: "{{ common_firewall_iptables_disable_services }}"
  become: yes
  tags:
    - common
    - common-firewall
    - common-firewall-service

- name: "Common | Firewall | IPTables | Enable iptables service"
  ansible.builtin.service:
    name: "{{ common_firewall_iptables_service }}"
    enabled: yes
    state: started
  become: yes
  tags:
    - common
    - common-firewall
    - common-firewall-service

- name: "Common | Firewall | IPTables | IPTables flush handlers"
  ansible.builtin.meta: flush_handlers
  tags:
    - common
    - common-firewall
    - common-firewall-service
