# code: language=ansible
---

- name: "Common | Firewall | {{ common_firewall_backend | default(common_firewall_default_backend) }}"
  ansible.builtin.include_tasks: "firewall/{{ common_firewall_backend | default(common_firewall_default_backend) }}/main.yml"
  when:
    - common_firewall_backend | default(common_firewall_default_backend) | is_ne_str
    - common_firewall_backend | default(common_firewall_default_backend) in ["iptables", "firewalld", "ufw"]
  tags:
    - common
    - common-firewall
    - common-firewall-install
    - common-firewall-configure
