# code: language=ansible
---

- name: "Common | Sudo | Install | Apt"
  ansible.builtin.apt:
    name: "sudo"
    state: present
    update_cache: false
    force_apt_get: true
    cache_valid_time: 3600
  become: true
  tags:
    - common
    - common-sudo
    - common-sudo-install
