# code: language=ansible
---

- name: "Common | Sudo | Install | Apt"
  ansible.builtin.apt:
    name: "sudo"
    state: present
    update_cache: no
    force_apt_get: yes
    cache_valid_time: 3600
  become: yes
  tags:
    - common
    - common-sudo
    - common-sudo-install
