# code: language=ansible
---

- name: "Common | Sudo | Install | Dnf"
  ansible.builtin.dnf:
    name: "sudo"
    state: present
    update_cache: no
  become: yes
  become_user: "{{ ansible_become_user }}"
  tags:
    - common
    - common-sudo
    - common-sudo-install
