# code: language=ansible
---

- name: "Common | ZSH | Install | Apt"
  ansible.builtin.apt:
    name:
      - "git"
      - "tar"
      - "zsh"
    state: "present"
    update_cache: no
    force_apt_get: yes
    cache_valid_time: 3600
  become: yes
  tags:
    - common
    - common-zsh
    - common-zsh-install
