# code: language=ansible
---

- name: "Common | ZSH | Install | Dnf"
  ansible.builtin.dnf:
    name:
      - "git"
      - "tar"
      - "zsh"
    state: "present"
    update_cache: no
  become: yes
  become_user: "{{ ansible_become_user }}"
  tags:
    - common
    - common-zsh
    - common-zsh-install
