# code: language=ansible
---

- name: "Common | Rootkit Hunter | Install | Apt"
  ansible.builtin.apt:
    name: "{{ common_rkhunter_packages }}"
    state: present
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600
  notify:
    - Update rkhunter
  become: true
  tags:
    - common
    - common-rkhunter
    - common-rkhunter-install
