# code: language=ansible
---

- name: "Common | Rootkit Hunter | Install | Dnf"
  ansible.builtin.dnf:
    name: "{{ common_rkhunter_packages }}"
    state: present
    update_cache: false
  notify:
    - update rkhunter
  become: true
  tags:
    - common
    - common-rkhunter
    - common-rkhunter-install
