# code: language=ansible
---

- name: "Common | Rootkit Hunter | Install"
  ansible.builtin.include_tasks: "rkhunter/install/{{ os.pkg }}.yml"
  tags:
    - common
    - common-rkhunter
    - common-rkhunter-install

- name: "Common | Rootkit Hunter | Configure"
  ansible.builtin.lineinfile:
    path: "{{ common_rkhunter_config }}"
    line: "{{ item.option }}={{ item.value }}"
    regexp: "^{{ item.option }}={{ item.value }}"
    state: "{{ item.state | default('present') }}"
    owner: "root"
    group: "root"
    mode: "0644"
    backup: false
  with_items: "{{ common_rkhunter_options | default([]) }}"
  when:
    - common_rkhunter_options | default([]) | is_ne_list_dicts
  become: true
  tags:
    - common
    - common-rkhunter
    - common-rkhunter-configure

- name: "Common | Rootkit Hunter | Flush handlers"
  ansible.builtin.meta: flush_handlers
  tags:
    - common
    - common-rkhunter
    - common-rkhunter-configure
    - common-rkhunter-install
