---

# 00 # Always

- name: "Common | Always"
  ansible.builtin.include_tasks: "always/main.yml"
  tags:
    - always

# 01 # Hostname

- name: "Common | Hostname"
  ansible.builtin.include_tasks: "hostname/main.yml"
  when:
    - common_hostname is defined
    - common_hostname | type_debug == 'AnsibleUnicode'
    - common_hostname | length > 0
  tags:
    - common
    - common-hostname

# 02 # Hosts

- name: "Common | Hosts"
  ansible.builtin.include_tasks: "hosts/main.yml"
  when:
    - common_hosts is defined
    - common_hosts | type_debug == 'list'
    - common_hosts | length > 0
  tags:
    - common
    - common-hosts

# 03 # Timezone

- name: "Common | Timezone"
  ansible.builtin.include_tasks: "timezone/main.yml"
  when:
    - common_timezone is defined
    - common_timezone | type_debug == 'AnsibleUnicode'
    - common_timezone | length > 0
  tags:
    - common
    - common-timezone

# 04 # Users

- name: "Common | Users"
  ansible.builtin.include_tasks: "users/main.yml"
  when:
    - common_users is defined
    - common_users | type_debug == 'list'
    - common_users | length > 0
  tags:
    - common
    - common-users

# 05 # Dirs

- name: "Common | Dirs"
  ansible.builtin.include_tasks: "dirs/main.yml"
  when:
    - common_dirs is defined
    - common_dirs | type_debug == 'list'
    - common_dirs | length > 0
  tags:
    - common
    - common-dirs
