# code: language=ansible
---

# 00 # Always

- name: "Common | Always"
  ansible.builtin.include_tasks: "always/main.yml"
  tags:
    - always

# 01 # Hostname

- name: "Common | Hostname"
  ansible.builtin.include_tasks: "hostname/main.yml"
  when:
    - common_hostname | is_ne_str
  tags:
    - common
    - common-hostname

# 02 # Hosts

- name: "Common | Hosts"
  ansible.builtin.include_tasks: "hosts/main.yml"
  when:
    - common_hosts | is_ne_list_dicts
  tags:
    - common
    - common-hosts

# 03 # Timezone

- name: "Common | Timezone"
  ansible.builtin.include_tasks: "timezone/main.yml"
  when:
    - common_timezone | is_ne_str
  tags:
    - common
    - common-timezone

# 04 # Repositories

- name: "Common | Repositories"
  ansible.builtin.include_tasks: "repositories/{{ dist_pkg_mgr }}.yml"
  when:
    - common_repositories_manager | is_ne_list_dicts or
      common_repositories_add | is_ne_list_dicts or
      common_repositories_enable | is_ne_list
  tags:
    - common
    - common-repositories
    - common-repositories-manager
    - common-repositories-gpg-keys
    - common-repositories-add
    - common-repositories-enable
    - common-repositories-disable

# 05 # Packages

- name: "Common | Packages"
  ansible.builtin.include_tasks: "packages/{{ dist_pkg_mgr }}.yml"
  when:
    - common_packages | is_ne_list or
      common_packages_additional | is_ne_list
  tags:
    - common
    - common-packages

# 06 # Locales

- name: "Common | Locale"
  ansible.builtin.include_tasks: "locale/main.yml"
  when:
    - common_locale | is_ne_str
  tags:
    - common
    - common-locale

# 07 # Users

- name: "Common | Users"
  ansible.builtin.include_tasks: "users/main.yml"
  when:
    - common_users | is_ne_list_dicts
  tags:
    - common
    - common-users

# 08 # Sudo

- name: "Common | Sudo"
  ansible.builtin.include_tasks: "sudo/main.yml"
  when:
    - common_sudo | is_ne_list_dicts
  tags:
    - common
    - common-sudo
    - common-sudo-install
    - common-sudo-configure

# 09 # SSH

- name: "Common | SSH"
  ansible.builtin.include_tasks: "ssh/main.yml"
  when:
    - common_ssh_authorized_keys | is_ne_list_dicts or
      common_ssh_keys | is_ne_list_dicts
  tags:
    - common
    - common-ssh

# 10 # Dirs

- name: "Common | Dirs"
  ansible.builtin.include_tasks: "dirs/main.yml"
  when:
    - common_dirs | is_ne_list_dicts
  tags:
    - common
    - common-dirs

# 11 # Environments

- name: "Common | Environments"
  ansible.builtin.include_tasks: "environments/main.yml"
  when:
    - common_environments | is_ne_list_dicts
  tags:
    - common
    - common-environments

# 12 # Limits

- name: "Common | Limits"
  ansible.builtin.include_tasks: "limits/main.yml"
  when:
    - common_limits | is_ne_list_dicts
  tags:
    - common
    - common-limits

# 13 # Sysctl

- name: "Common | Sysctl"
  ansible.builtin.include_tasks: "sysctl/main.yml"
  when:
    - common_sysctl_keys | is_ne_list_dicts
  tags:
    - common
    - common-sysctl

# 14 # Sysfs

- name: "Common | Sysfs"
  ansible.builtin.include_tasks: "sysfs/main.yml"
  when:
    - common_sysfs | is_ne_list_dicts
  tags:
    - common
    - common-sysfs
    - common-sysfs-install
    - common-sysfs-configure

# 15 # Tuned

- name: "Common | Tuned"
  ansible.builtin.include_tasks: "tuned/main.yml"
  when:
    - common_tuned_enable
  tags:
    - common
    - common-tuned
    - common-tuned-install
    - common-tuned-configure

# 16 # Firewall

- name: "Common | Firewall"
  ansible.builtin.include_tasks: "firewall/main.yml"
  when:
    - common_firewall | is_ne_dict
  tags:
    - common
    - common-firewall
    - common-firewall-install
    - common-firewall-configure

# 17 # SELinux

- name: "Common | SELinux"
  ansible.builtin.include_tasks: "selinux/main.yml"
  when:
    - common_selinux_enable
    - dist_name in ["alma", "centos", "oracle", "rocky"]
  tags:
    - common
    - common-selinux
    - common-selinux-install
    - common-selinux-configure

# 18 # AIDE

- name: "Common | AIDE"
  ansible.builtin.include_tasks: "aide/main.yml"
  when:
    - common_aide_enable
  tags:
    - common
    - common-aide
    - common-aide-install
    - common-aide-configure

# 19 # Atop

- name: "Common | Atop"
  ansible.builtin.include_tasks: "atop/main.yml"
  when:
    - common_atop_enable
  tags:
    - common
    - common-atop
    - common-atop-install
    - common-atop-configure

# 20 # Auditd

- name: "Common | Auditd"
  ansible.builtin.include_tasks: "auditd/main.yml"
  when:
    - common_auditd_enable
  tags:
    - common
    - common-auditd
    - common-auditd-install
    - common-auditd-configure

# 21 # Chrony

- name: "Common | Chrony"
  ansible.builtin.include_tasks: "chrony/main.yml"
  when:
    - common_chrony_enable
  tags:
    - common
    - common-chrony
    - common-chrony-install
    - common-chrony-configure

# 22 # Cron

- name: "Common | Cron"
  ansible.builtin.include_tasks: "cron/main.yml"
  when:
    - common_cron_environments | is_ne_list_dicts or
      common_cron_tasks | is_ne_list_dicts
  tags:
    - common
    - common-cron
    - common-cron-install
    - common-cron-configure

# 23 # Logwatch

- name: "Common | Logwatch"
  ansible.builtin.include_tasks: "logwatch/main.yml"
  when:
    - common_logwatch_enable
  tags:
    - common
    - common-logwatch
    - common-logwatch-install
    - common-logwatch-configure

# 24 # NSCD

- name: "Common | NSCD"
  ansible.builtin.include_tasks: "nscd/main.yml"
  when:
    - common_nscd_enable
  tags:
    - common
    - common-nscd
    - common-nscd-install
    - common-nscd-configure

# 25 # Rootkit Hunter

- name: "Common | Rootkit Hunter"
  ansible.builtin.include_tasks: "rkhunter/main.yml"
  when:
    - common_rkhunter_enable
  tags:
    - common
    - common-rkhunter
    - common-rkhunter-install
    - common-rkhunter-configure

# 26 # Smartmontools

- name: "Common | Smartmontools"
  ansible.builtin.include_tasks: "smartmontools/main.yml"
  when:
    - common_smartmontools_enable
  tags:
    - common
    - common-smartmontools
    - common-smartmontools-install
    - common-smartmontools-configure

# 27 # SSHD

- name: "Common | SSHD"
  ansible.builtin.include_tasks: "sshd/main.yml"
  when:
    - common_sshd_options | is_ne_list_dicts
  tags:
    - common
    - common-sshd
    - common-sshd-install
    - common-sshd-configure

# 28 # ZSH

- name: "Common | ZSH"
  ansible.builtin.include_tasks: "zsh/main.yml"
  when:
    - common_zsh | is_ne_list_dicts or
      common_zsh_additional | is_ne_list_dicts
  tags:
    - common
    - common-zsh
    - common-zsh-install
    - common-zsh-configure
