---

# 00 # Always

#- name: "Common | Always"
#  ansible.builtin.include_tasks: "always/main.yml"
#  tags:
#    - always

# 01 # Hostname

- name: "Common | Hostname"
  ansible.builtin.include_tasks: "hostname/main.yml"
  when:
    - common_hostname | is_ne_string
  tags:
    - common
    - common-hostname

# 02 # Hosts

- name: "Common | Hosts"
  ansible.builtin.include_tasks: "hosts/main.yml"
  when:
    - common_hosts | is_dicts_list
  tags:
    - common
    - common-hosts

# 03 # Timezone

- name: "Common | Timezone"
  ansible.builtin.include_tasks: "timezone/main.yml"
  when:
    - common_timezone | is_ne_string
  tags:
    - common
    - common-timezone

# 04 # Repositories

- name: "Common | Repositories"
  ansible.builtin.include_tasks: "repositories/{{ dist_pkg_mgr }}.yml"
  when:
    - common_repositories_manager | is_dicts_list or
      common_repositories_add | is_dicts_list or
      common_repositories_enable | is_ne_list
  tags:
    - common
    - common-repositories
    - common-repositories-manager
    - common-repositories-gpg-keys
    - common-repositories-add
    - common-repositories-enable
    - common-repositories-disable

# 05 # Packages

- name: "Common | Packages"
  ansible.builtin.include_tasks: "packages/{{ dist_pkg_mgr }}.yml"
  tags:
    - common
    - common-packages

# 06 # Locales

- name: "Common | Locale"
  ansible.builtin.include_tasks: "locale/main.yml"
  when:
    - common_locale | is_ne_string
  tags:
    - common
    - common-locale

# 07 # Users

- name: "Common | Users"
  ansible.builtin.include_tasks: "users/main.yml"
  when:
    - common_users | is_dicts_list
  tags:
    - common
    - common-users

# 08 # Dirs

- name: "Common | Dirs"
  ansible.builtin.include_tasks: "dirs/main.yml"
  when:
    - common_dirs | is_dicts_list
  tags:
    - common
    - common-dirs

# 09 # Environments

- name: "Common | Environments"
  ansible.builtin.include_tasks: "environments/main.yml"
  when:
    - common_environments | is_dicts_list
  tags:
    - common
    - common-environments

# 10 # Limits

- name: "Common | Limits"
  ansible.builtin.include_tasks: "limits/main.yml"
  when:
    - common_limits is_dicts_list
  tags:
    - common
    - common-limits

# 11 # Sysctl

- name: "Common | Sysctl"
  ansible.builtin.include_tasks: "sysctl/main.yml"
  when:
    - common_sysctl_keys | is_dicts_list
  tags:
    - common
    - common-sysctl
