---

# 00 # Always

- name: "Common | Always"
  ansible.builtin.include_tasks: "always/main.yml"
  tags:
    - always

# 01 # Hostname

- name: "Common | Hostname"
  ansible.builtin.include_tasks: "hostname/main.yml"
  when:
    - common_hostname is defined
    - common_hostname is string
    - common_hostname | length > 0
  tags:
    - common
    - common-hostname

# 02 # Hosts

- name: "Common | Hosts"
  ansible.builtin.include_tasks: "hosts/main.yml"
  when:
    - common_hosts is defined
    - common_hosts | type_debug == 'list'
    - common_hosts | length > 0
  tags:
    - common
    - common-hosts

# 03 # Timezone

- name: "Common | Timezone"
  ansible.builtin.include_tasks: "timezone/main.yml"
  when:
    - common_timezone is defined
    - common_timezone is string
    - common_timezone | length > 0
  tags:
    - common
    - common-timezone

# 04 # Users

- name: "Common | Users"
  ansible.builtin.include_tasks: "users/main.yml"
  when:
    - common_users is defined
    - common_users | type_debug == 'list'
    - common_users | length > 0
  tags:
    - common
    - common-users

# 05 # Dirs

- name: "Common | Dirs"
  ansible.builtin.include_tasks: "dirs/main.yml"
  when:
    - common_dirs is defined
    - common_dirs | type_debug == 'list'
    - common_dirs | length > 0
  tags:
    - common
    - common-dirs

# 06 # Packages

- name: "Common | Packages"
  ansible.builtin.include_tasks: "packages/{{ dist_pkg_mgr }}.yml"
  tags:
    - common
    - common-packages

# 07 # Locales

- name: "Common | Locale"
  ansible.builtin.include_tasks: "locale/main.yml"
  when:
    - common_locale is defined
    - common_locale is string
    - common_locale | length > 0
  tags:
    - common
    - common-locale

# 08 # Environments

- name: "Common | Environments"
  ansible.builtin.include_tasks: "environments/main.yml"
  when:
    - common_environments is defined
    - common_environments | type_debug == 'list'
    - common_environments | length > 0
  tags:
    - common
    - common-environments

# 09 # Limits

- name: "Common | Limits"
  ansible.builtin.include_tasks: "limits/main.yml"
  when:
    - common_limits is defined
    - common_limits | type_debug == 'list'
    - common_limits | length > 0
  tags:
    - common
    - common-limits

# 10 # Sysctl

- name: "Common | Sysctl"
  ansible.builtin.include_tasks: "sysctl/main.yml"
  when:
    - common_sysctl_keys is defined
    - common_sysctl_keys | type_debug == 'list'
    - common_sysctl_keys | length > 0
  tags:
    - common
    - common-sysctl
