# code: language=ansible
---

- name: "Common | Chrony | Install | Apt"
  ansible.builtin.apt:
    name: "{{ common_chrony_packages }}"
    state: present
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600
  become: true
  tags:
    - common
    - common-chrony
    - common-chrony-install
