# code: language=ansible
---

- name: "Common | Chrony | Install | Dnf"
  ansible.builtin.dnf:
    name: "{{ common_chrony_packages }}"
    state: present
    update_cache: no
  become: yes
  become_user: "{{ ansible_become_user }}"
  tags:
    - common
    - common-chrony
    - common-chrony-install
