---

- name: "Common | Sudo | Install | Dnf"
  ansible.builtin.dnf:
    name: "sudo"
    state: present
    update_cache: true
  become: true
  tags:
    - common
    - common-sudo
    - common-sudo-install
