# code: language=ansible
---

- name: "Common | Sudo | Install"
  ansible.builtin.include_tasks: "sudo/install/{{ dist_pkg_mgr }}.yml"
  tags:
    - common
    - common-sudo
    - common-sudo-install

- name: "Common | Sudo | Configure"
  ansible.builtin.template:
    src: "sudo/sudoers.j2"
    dest: "/etc/sudoers.d/{% if item.name[1] == '%' %}group{% else %}user{% endif %}-{{ item.name | replace('%', '') | replace('.', '-') }}"
    mode: "0440"
    validate: 'visudo -cf %s'
  when:
    - item.name | default('') | is_ne_str
  with_items: "{{ common_sudo }}"
  become: yes
  become_user: "{{ ansible_become_user }}"
  tags:
    - common
    - common-sudo
    - common-sudo-configure
