# code: language=ansible
---

- name: "Common | Always | Install dependencies | Apt"
  ansible.builtin.apt:
    name: "{{ common_always_packages }}"
    state: present
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
  become: yes
  become_user: "{{ ansible_become_user }}"
  tags:
    - always
