# code: language=ansible
---

- name: "Common | Always | Install dependencies | Dnf"
  ansible.builtin.dnf:
    name: "{{ common_always_packages }}"
    state: present
    update_cache: yes
  become: yes
  become_user: "{{ ansible_become_user }}"
  tags:
    - always
