# code: language=ansible
---

- name: "Common | Firewall | IPTables | Install | Apt"
  ansible.builtin.apt:
    name:
      - "iptables"
      - "iptables-persistent"
      - "ipset"
      - "ipset-persistent"
    state: "present"
    update_cache: no
    force_apt_get: yes
    cache_valid_time: 3600
  become: yes
  become_user: "{{ ansible_become_user }}"
  tags:
    - common
    - common-firewall
    - common-firewall-install
