# code: language=ansible
---

- name: "Common | Firewall | IPTables | Install | Dnf / Yum"
  ansible.builtin.dnf:
    name:
      - "iptables{% if dist_version | int > 8 %}-nft{% endif %}"
      - "iptables{% if dist_version | int > 8 %}-nft{% endif %}-services"
      - "ipset"
      - "ipset-service"
    state: "present"
    update_cache: no
  become: yes
  tags:
    - common
    - common-firewall
    - common-firewall-install
