# code: language=ansible
---

- name: "Common | Firewall | IPTables | Install | Dnf / Yum"
  ansible.builtin.dnf:
    name:
      - "iptables"
      - "iptables-services"
      - "ipset"
      - "ipset-service"
    state: "present"
    update_cache: no
  become: yes
  become_user: "{{ ansible_become_user }}"
  tags:
    - common
    - common-firewall
    - common-firewall-install
