# code: language=ansible
---

- name: "Common | Logwatch | Install | Dnf"
  ansible.builtin.dnf:
    name: "{{ common_logwatch_packages }}"
    state: present
    update_cache: no
  become: yes
  tags:
    - common
    - common-logwatch
    - common-logwatch-install
