# code: language=ansible
---

- name: "Common | AIDE | Install | Apt"
  ansible.builtin.apt:
    name: "{{ common_aide_packages }}"
    state: present
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600
  become: true
  tags:
    - common
    - common-aide
    - common-aide-install
