# code: language=ansible
---

- name: "Common | AIDE | Install | Dnf"
  ansible.builtin.dnf:
    name: "{{ common_aide_packages }}"
    state: present
    update_cache: no
  become: yes
  become_user: "{{ ansible_become_user }}"
  tags:
    - common
    - common-aide
    - common-aide-install
