# code: language=ansible
---

- name: "Common | Environments | System"
  ansible.builtin.template:
    src: "environments/system.sh.j2"
    dest: "/etc/profile.d/system.sh"
    owner: "root"
    group: "root"
    mode: "0644"
    backup: no
  become: yes
  tags:
    - common
    - common-environments

- name: "Common | Environments | Create user config directory"
  ansible.builtin.file:
    path: "~{{ item.user }}/.config/shell"
    state: "directory"
    owner: "{{ item.user }}"
    mode: "0700"
    follow: yes
  become: yes
  with_items: "{{ common_environments }}"
  when:
    - item.user | is_ne_str
  tags:
    - common
    - common-environments

- name: "Common | Environments | User"
  ansible.builtin.template:
    src: "environments/user.sh.j2"
    dest: "~{{ item.user }}/.config/shell/env.sh"
    owner: "{{ item.user }}"
    mode: "0700"
    backup: no
  become: yes
  with_items: "{{ common_environments }}"
  when:
    - item.user | is_ne_str
  tags:
    - common
    - common-environments
