# code: language=ansible
---

- name: "Common | Rootkit Hunter | Install | Apt"
  ansible.builtin.apt:
    name: "{{ common_rkhunter_packages }}"
    state: present
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
  notify:
    - Update rkhunter
    - Prop update rkhunter
  become: yes
  become_user: "{{ ansible_become_user }}"
  tags:
    - common
    - common-rkhunter
    - common-rkhunter-install
