# code: language=ansible
---

- name: "Common | Rootkit Hunter | Install | Dnf"
  ansible.builtin.dnf:
    name: "{{ common_rkhunter_packages }}"
    state: present
    update_cache: no
  notify:
    - Update rkhunter
    - Prop update rkhunter
  become: yes
  tags:
    - common
    - common-rkhunter
    - common-rkhunter-install
