# code: language=ansible
---

- name: "Common | Cron | Install | Apt"
  ansible.builtin.apt:
    name: "{{ common_cron_packages }}"
    state: present
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600
  become: true
  tags:
    - common
    - common-cron
    - common-cron-install
