# code: language=ansible
---

- name: "Common | ZSH | Install | Apt"
  ansible.builtin.apt:
    name:
      - "git"
      - "tar"
      - "zsh"
    state: "present"
    update_cache: false
    force_apt_get: true
    cache_valid_time: 3600
  become: true
  tags:
    - common
    - common-zsh
    - common-zsh-install
