# code: language=ansible
---

- name: "Common | ZSH | Install | Dnf"
  ansible.builtin.dnf:
    name:
      - "git"
      - "tar"
      - "zsh"
    state: "present"
    update_cache: true
  become: true
  tags:
    - common
    - common-zsh
    - common-zsh-install
