# code: language=ansible
---

- name: "Common | ZSH | Install"
  ansible.builtin.include_tasks: "zsh/install/{{ dist_pkg_mgr }}.yml"
  tags:
    - common
    - common-zsh
    - common-zsh-install

- name: "Common | ZSH | Install | Merge users"
  ansible.builtin.set_fact:
    _common_zsh_: "{{ [common_zsh | default([]), common_zsh_additional | default([])] | community.general.lists_mergeby('user') }}"
  tags:
    - common
    - common-zsh
    - common-zsh-configure

- name: "Common | ZSH | Install | Merge users | Debug"
  ansible.builtin.debug:
    msg: "{{ _common_zsh_ }}"
    verbosity: 1
  tags:
    - common
    - common-zsh
    - common-zsh-configure

- name: "Common | ZSH | Install OMZ"
  ansible.builtin.git:
    repo: "https://github.com/ohmyzsh/ohmyzsh.git"
    dest: "~{{ item.user }}/.oh-my-zsh"
    version: "{{ common_zsh_omz_version }}"
    single_branch: yes
    clone: yes
    update: no
  become: yes
  become_user: "{{ item.user }}"
  with_items: "{{ _common_zsh_ }}"
  tags:
    - common
    - common-zsh
    - common-zsh-configure

- name: "Common | ZSH | Install P10K"
  ansible.builtin.git:
    repo: "https://github.com/romkatv/powerlevel10k.git"
    dest: "~{{ item.user }}/.oh-my-zsh/custom/themes/powerlevel10k"
    version: "{{ common_zsh_p10k_version }}"
    single_branch: yes
    depth: 1
    clone: yes
    update: no
  become: yes
  become_user: "{{ item.user }}"
  with_items: "{{ _common_zsh_ }}"
  tags:
    - common
    - common-zsh
    - common-zsh-configure

- name: "Common | ZSH | Install | Plugin | Autosuggestions"
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "~{{ item.user }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    version: "v{{ common_zsh_autosuggestions_version }}"
    single_branch: yes
    depth: 1
    clone: yes
    update: no
  become: yes
  become_user: "{{ item.user }}"
  with_items: "{{ _common_zsh_ }}"
  tags:
    - common
    - common-zsh
    - common-zsh-configure

- name: "Common | ZSH | Install | Plugin | Syntax Highlighting"
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "~{{ item.user }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    version: "{{ common_zsh_syntax_highlighting_version }}"
    single_branch: yes
    depth: 1
    clone: yes
    update: no
  become: yes
  become_user: "{{ item.user }}"
  with_items: "{{ _common_zsh_ }}"
  tags:
    - common
    - common-zsh
    - common-zsh-configure

- name: "Common | ZSH | Configure ZSH"
  ansible.builtin.copy:
    src: "zsh/.zshrc"
    dest: "~{{ item.user }}/.zshrc"
    owner: "{{ item.user }}"
    mode: "0644"
    backup: no
  become: yes
  become_user: "{{ item.user }}"
  with_items: "{{ _common_zsh_ }}"
  tags:
    - common
    - common-zsh
    - common-zsh-configure

- name: "Common | ZSH | Configure P10K"
  ansible.builtin.copy:
    src: "zsh/.p10k.zsh"
    dest: "~{{ item.user }}/.p10k.zsh"
    owner: "{{ item.user }}"
    mode: "0644"
    backup: no
  become: yes
  become_user: "{{ item.user }}"
  with_items: "{{ _common_zsh_ }}"
  tags:
    - common
    - common-zsh
    - common-zsh-configure

- name: "Common | ZSH | Create user config directory"
  ansible.builtin.file:
    path: "~{{ item.user }}/.config/zsh"
    state: "directory"
    owner: "{{ item.user }}"
    mode: "0700"
    follow: yes
  become: yes
  become_user: "{{ item.user }}"
  with_items: "{{ _common_zsh_ }}"
  tags:
    - common
    - common-zsh
    - common-zsh-configure

- name: "Common | ZSH | Configure aliases"
  ansible.builtin.copy:
    src: "zsh/aliases.zsh"
    dest: "~{{ item.user }}/.config/zsh/aliases.zsh"
    owner: "{{ item.user }}"
    mode: "0600"
    backup: no
  become: yes
  become_user: "{{ item.user }}"
  with_items: "{{ _common_zsh_ }}"
  tags:
    - common
    - common-zsh
    - common-zsh-configure
