# code: language=ansible
---

- name: "Common | Tuned | Install | Apt"
  ansible.builtin.apt:
    name: "{{ common_tuned_packages }}"
    state: "present"
    update_cache: false
    force_apt_get: true
    cache_valid_time: 3600
  become: true
  tags:
    - common
    - common-tuned
    - common-tuned-install
