# code: language=ansible
---

- name: "Common | Firewall | Firewalld | Install | Apt"
  ansible.builtin.apt:
    name:
      - "firewalld"
    state: "present"
    update_cache: true
    force_apt_get: true
    cache_valid_time: 600
  become: true
  tags:
    - common
    - common-firewall
    - common-firewall-install
