# code: language=ansible
---

- name: "Common | Firewall | Firewalld | Install | Dnf / Yum"
  ansible.builtin.dnf:
    name:
      - "firewalld"
      - "firewalld-filesystem"
    state: "present"
    update_cache: true
  become: true
  tags:
    - common
    - common-firewall
    - common-firewall-install
