---

ansible_python_interpreter: "/usr/bin/python3.11"

# 04 # Repositories

common_repositories_enable:
  - "crb"
  - "extras"
  - "highavailability"
  - "plus"

# 25 # Rootkit Hunter

common_rkhunter_options:
  - option: "ALLOW_SSH_ROOT_USER"
    value: "yes"
  - option: "SCRIPTWHITELIST"
    value: "/usr/bin/fgrep"
  - option: "SCRIPTWHITELIST"
    value: "/usr/bin/egrep"
