# code: language=ansible
---

- name: "Common | Always | Install dependencies | Apt"
  ansible.builtin.apt:
    name: "{{ __always_packages__ }}"
    state: present
    update_cache: true
    force_apt_get: true
    cache_valid_time: 600
  become: true
  tags:
    - always
