# code: language=ansible
---

- name: "Common | Always | Install dependencies | Dnf"
  ansible.builtin.dnf:
    name: "{{ __always_packages__ }}"
    state: present
    update_cache: true
  become: true
  tags:
    - always
