# code: language=ansible
---

# Check distribution and version before run tasks

- name: "Common | Always | Check | OS"
  ansible.builtin.fail:
    msg: "Unsupported distribution {{ os.name }}"
  when:
    - os.name not in ["alma", "centos", "debian", "oracle", "rocky", "ubuntu"]
  tags:
    - always

- name: "Common | Always | Check | Version of Alma / Centos / Oracle/ Rocky linux"
  ansible.builtin.fail:
    msg: "Unsupported distribution version {{ os.name }}: {{ os.version }}"
  when:
    - os.name in ["alma", "centos", "oracle", "rocky"]
    - os.version not in ["8", "9"]
  tags:
    - always

- name: "Common | Always | Check | Codename of Debian / Ubuntu linux"
  ansible.builtin.fail:
    msg: "Unsupported distribution version {{ os.name }}: {{ os.codename }}"
  when:
    - os.name in ["debian", "ubuntu"]
    - os.codename not in ["buster", "bullseye", "bookworm", "focal", "jammy", "noble"]
  tags:
    - always

# Include distribution specified vars

- name: "Common | Always | Include | OS specific vars"
  ansible.builtin.include_vars: "{{ os.name }}.yml"
  tags:
    - always

# Install role packages dependencies

- name: "Common | Always | Install | Packages"
  ansible.builtin.include_tasks: "always/install/{{ os.pkg }}.yml"
  when:
    - common_always_packages | is_ne_list
  tags:
    - always

- name: "Common | Always | Facts | Services"
  ansible.builtin.service_facts:
  tags:
    - always
