# code: language=ansible
---

- name: "Common | Packages | Install | Apt"
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present
    update_cache: false
    force_apt_get: true
    cache_valid_time: 3600
  when:
    - common_packages | is_ne_list
  become: true
  tags:
    - common
    - common-packages

- name: "Common | Packages | Install Additional | Apt"
  ansible.builtin.apt:
    name: "{{ common_packages_additional }}"
    state: present
    update_cache: false
    force_apt_get: true
    cache_valid_time: 3600
  when:
    - common_packages_additional | is_ne_list
  become: true
  tags:
    - common
    - common-packages
