---

- name: "Common | Packages | Install | Apt"
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present
    update_cache: true
    force_apt_get: true
    cache_valid_time: 600
  when:
    - common_packages is defined
    - common_packages | type_debug == 'list'
    - common_packages | length > 0
  become: true
  tags:
    - common
    - common-packages

- name: "Common | Packages | Install Additional | Apt"
  ansible.builtin.apt:
    name: "{{ common_packages_additional }}"
    state: present
    update_cache: true
    force_apt_get: true
    cache_valid_time: 600
  when:
    - common_packages_additional is defined
    - common_packages_additional | type_debug == 'list'
    - common_packages_additional | length > 0
  become: true
  tags:
    - common
    - common-packages
