# code: language=ansible
---

- name: "Common | Packages | Install | Apt | Merge packages"
  ansible.builtin.set_fact:
    _common_packages_: "{{ (common_packages | default([]) + common_packages_additional | default([])) | unique }}"
  tags:
    - common
    - common-packages

- name: "Common | Packages | Install | Apt | Merge packages | Debug"
  ansible.builtin.debug:
    msg: "{{ _common_packages_ }}"
    verbosity: 1
  tags:
    - common
    - common-packages

- name: "Common | Packages | Install | Apt"
  ansible.builtin.apt:
    name: "{{ _common_packages_ }}"
    state: present
    update_cache: false
    force_apt_get: true
    cache_valid_time: 3600
  when:
    - _common_packages_ | is_ne_list
  become: true
  tags:
    - common
    - common-packages
