# code: language=ansible
---

- name: "Common | Packages | Install | Dnf"
  ansible.builtin.dnf:
    name: "{{ common_packages }}"
    state: present
    update_cache: no
  when:
    - common_packages | is_ne_list
  become: yes
  become_user: "{{ ansible_become_user }}"
  tags:
    - common
    - common-packages

- name: "Common | Packages | Install Additional | Dnf"
  ansible.builtin.dnf:
    name: "{{ common_packages_additional }}"
    state: present
    update_cache: no
  when:
    - common_packages_additional | is_ne_list
  become: yes
  become_user: "{{ ansible_become_user }}"
  tags:
    - common
    - common-packages
