# code: language=ansible
---

- name: "Common | Packages | Install | Dnf | Merge packages"
  ansible.builtin.set_fact:
    _common_packages_: "{{ (common_packages | default([]) + common_packages_additional | default([])) | unique }}"
  tags:
    - common
    - common-packages

- name: "Common | Packages | Install | Dnf | Merge packages | Debug"
  ansible.builtin.debug:
    msg: "{{ _common_packages_ }}"
    verbosity: 1
  tags:
    - common
    - common-packages

- name: "Common | Packages | Install | Dnf"
  ansible.builtin.dnf:
    name: "{{ _common_packages_ }}"
    state: present
    update_cache: false
  when:
    - _common_packages_ | is_ne_list
  become: true
  tags:
    - common
    - common-packages
