# code: language=ansible
---

- name: "Common | Packages | Install | Dnf"
  ansible.builtin.dnf:
    name: "{{ common_packages }}"
    state: present
    update_cache: true
  when:
    - common_packages | is_ne_list
  become: true
  tags:
    - common
    - common-packages

- name: "Common | Packages | Install Additional | Dnf"
  ansible.builtin.dnf:
    name: "{{ common_packages_additional }}"
    state: present
    update_cache: true
  when:
    - common_packages_additional | is_ne_list
  become: true
  tags:
    - common
    - common-packages
