---
dependency:
  name: galaxy

driver:
  name: docker

scenario:
  name: "docker-co-9"

platforms:
  # CentOS Linux 9 Stream
  - name: "centos-linux-9"
    image: "reg.sys.im/tools-molecule-systemd:co-9"
    privileged: true
    pre_build_image: true
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    security_opt:
      - seccomp=unconfined
    capabilities:
      - CAP_SYS_ADMIN
    override_command: false
    cgroupns: private
    groups:
      - alma
      - el

provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: true
  options:
    vvv: true
  inventory:
    links:
      host_vars: ../.inventory/host_vars
      group_vars: ../.inventory/group_vars

verifier:
  name: ansible
