# code: language=ansible
---

- name: "Common | Smartmontools | Install | Apt"
  ansible.builtin.apt:
    name: "{{ common_smartmontools_packages }}"
    state: present
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
  become: yes
  tags:
    - common
    - common-smartmontools
    - common-smartmontools-install
