# code: language=ansible
---

- name: "Common | Smartmontools | Install | Dnf"
  ansible.builtin.dnf:
    name: "{{ common_smartmontools_packages }}"
    state: present
    update_cache: no
  become: yes
  become_user: "{{ ansible_become_user }}"
  tags:
    - common
    - common-smartmontools
    - common-smartmontools-install
