# code: language=ansible
---

- name: "Common | Sysfs | Install | Apt"
  ansible.builtin.apt:
    name: "sysfsutils"
    state: "present"
    update_cache: no
    force_apt_get: yes
    cache_valid_time: 3600
  become: yes
  tags:
    - common
    - common-sysfs
    - common-sysfs-install
