# code: language=ansible
---

- name: "Common | Sysfs | Install | Dnf"
  ansible.builtin.dnf:
    name: "sysfsutils"
    state: "present"
    update_cache: no
  become: yes
  become_user: "{{ ansible_become_user }}"
  tags:
    - common
    - common-sysfs
    - common-sysfs-install
