# code: language=ansible
---

- name: "Common | NSCD | Install | Dnf"
  ansible.builtin.dnf:
    name: "{{ common_nscd_packages }}"
    state: present
    update_cache: no
  become: yes
  tags:
    - common
    - common-nscd
    - common-nscd-install
