# code: language=ansible
---

- name: "Common | Cron | Install | Dnf"
  ansible.builtin.dnf:
    name: "{{ common_cron_packages }}"
    state: present
    update_cache: no
  become: yes
  tags:
    - common
    - common-cron
    - common-cron-install
