---
dependency:
  name: galaxy

driver:
  name: docker

scenario:
  name: "docker-rl-9"

platforms:
  # Rocky Linux 9
  - name: "rocky-linux-9"
    image: "reg.sys.im/tools-molecule-systemd:rl-9"
    privileged: true
    pre_build_image: true
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    security_opt:
      - seccomp=unconfined
    capabilities:
      - CAP_SYS_ADMIN
    override_command: false
    cgroupns: private
    cgroup_parent: "docker.slice"
    groups:
      - alma
      - el

provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: true
  options:
    vvv: true
  inventory:
    links:
      .files: ../.inventory/.files
      host_vars: ../.inventory/host_vars
      group_vars: ../.inventory/group_vars

verifier:
  name: ansible
