---

common_repositories_enable:
  - "crb"
  - "extras"
  - "powertools"
  - "plus"

common_rkhunter_options:
  - option: "ALLOW_SSH_ROOT_USER"
    value: "yes"
  - option: "SCRIPTWHITELIST"
    value: "/usr/bin/fgrep"
  - option: "SCRIPTWHITELIST"
    value: "/usr/bin/egrep"
