# code: language=ansible
---

- name: "Common | Tuned | Install | Dnf"
  ansible.builtin.dnf:
    name: "{{ common_tuned_packages }}"
    state: "present"
    update_cache: no
  become: yes
  become_user: "{{ ansible_become_user }}"
  tags:
    - common
    - common-tuned
    - common-tuned-install
