# code: language=ansible
---

- name: "Common | Sysfs | Install | Apt"
  ansible.builtin.apt:
    name: "sysfsutils"
    state: "present"
    update_cache: false
    force_apt_get: true
    cache_valid_time: 3600
  become: true
  tags:
    - common
    - common-sysfs
    - common-sysfs-install
