# code: language=ansible
---

- name: "Common | Sysfs | Install"
  ansible.builtin.include_tasks: "sysfs/install/{{ dist_pkg_mgr }}.yml"
  tags:
    - common
    - common-sysfs
    - common-sysfs-install

- name: "Common | Sysfs | Configure"
  ansible.builtin.template:
    src: "sysfs/sysfs.conf.j2"
    dest: "/etc/sysfs.conf"
    owner: "root"
    group: "root"
    mode: "0644"
    backup: no
  become: yes
  tags:
    - common
    - common-sysfs
    - common-sysfs-configure
