---

ansible_user: root

common_hostname: "{{ inventory_hostname }}"

common_timezone: "Etc/UTC"

common_packages:
  - "htop"
  - "mc"
  - "mlocate"
  - "nano"
  - "net-tools"
  - "rsync"
  - "screen"
  - "strace"
  - "telnet"
  - "unzip"
  - "zsh"

common_locale: "en_US.UTF-8"

common_users:
  - name: "molecule"
    shell: "/bin/zsh"
    append: true
    state: "present"

common_sudo:
  - name: "molecule"
    defaults:
      - "!requiretty"
      - "env_keep += 'SSH_CLIENT'"
      - "env_keep += 'SSH_CONNECTION'"
      - "env_keep += 'SSH_TTY'"
      - "env_keep += 'P9K_SSH'"
      - "env_keep += 'TZ'"
      - "secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"
    permissions:
      - host: "ALL"
        runas: "ALL"
        nopasswd: true
        cmd: "ALL"

common_dirs:
  - path: "/var/shared/backups"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0750"
    force: "false"
    follow: "true"

common_environments:
  - user: "root"
    variables:
      PATH: "${PATH}:${HOME}/.bin:${HOME}/bin"
      MOLECULE: "YES"
  - user: "molecule"
    variables:
      PATH: "${PATH}:${HOME}/.bin:${HOME}/bin"
      MOLECULE: "YES"

common_limits:
  - domain: "*"
    limit_type: "soft"
    limit_item: "nofile"
    value: "65536"
    use_max: true
  - domain: "*"
    limit_type: "hard"
    limit_item: "nofile"
    value: "65536"
    use_max: true

common_sysctl_file: "ansible-common.conf"
common_sysctl_keys:
  - name: "net.core.somaxconn"
    value: "65535"

common_sysfs:
  - attribute: "sys/kernel/mm/transparent_hugepage/enabled"
    value: "madvise"
    type: "attribute"

common_tuned_enable: true
common_tuned_profile_name: "molecule"
common_tuned_profile_config:
  - name: "main"
    params:
      - option: "summary"
        value: "Test"
      - option: "include"
        value: "throughput-performance"
  - name: "sysctl"
    params:
      - option: "vm.dirty_ratio"
        value: "30"
      - option: "vm.swappiness"
        value: "30"
  - name: "vm"
    params:
      - option: "transparent_hugepages"
        value: "never"

common_aide_enable: true
common_aide_config_file: "{{ inventory_dir }}/.files/{{ ansible_os_family | lower }}.aide.conf"

common_atop_enable: true
common_atop_options:
  - option: "LOGINTERVAL"
    value: "5"
  - option: "LOGGENERATIONS"
    value: "7"

common_chrony_enable: true

common_cron_environments:
  - user: "molecule"
    vars:
      - name: "MAILTO"
        value: "molecule@exmaple.com"

common_logwatch_enable: true
common_logwatch_mail_to: "molecule@example.com"
common_logwatch_mail_from: "logwatch@{{ inventory_hostname }}"
common_logwatch_hostname: "{{ inventory_hostname }}"

common_nscd_enable: true

common_rkhunter_enable: true

common_sshd_options:
  - option: "pub_key_authentication"
    value: "yes"
  - option: "password_authentication"
    value: "no"
  - option: "gss_api_authentication"
    value: "no"
  - option: "kerberos_authentication"
    value: "no"
  - option: "permit_root_login"
    value: "no"

common_zsh:
  - user: "root"
  - user: "molecule"
