---

ansible_user: root

# 01 # Hostname

common_hostname: "{{ inventory_hostname }}"

# 02 # Hosts

common_hosts:
  - name: "molecule"
    ip: "127.0.0.1"

# 03 # Timezone

common_timezone: "Etc/UTC"

# 04 # Repositories

# 05 # Packages

common_packages:
  - "htop"
  - "mc"
  - "mlocate"
  - "nano"
  - "net-tools"
  - "rsync"
  - "screen"
  - "strace"
  - "telnet"
  - "unzip"
  - "zsh"

# 06 # Locales

common_locale: "en_US.UTF-8"

# 07 # Users

common_users:
  - name: "molecule"
    shell: "/bin/zsh"
    append: yes
    state: "present"

# 08 # Sudo

common_sudo:
  - name: "molecule"
    defaults:
      - "!requiretty"
      - "env_keep += 'SSH_CLIENT'"
      - "env_keep += 'SSH_CONNECTION'"
      - "env_keep += 'SSH_TTY'"
      - "env_keep += 'P9K_SSH'"
      - "env_keep += 'TZ'"
      - "secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"
    permissions:
      - host: "ALL"
        runas: "ALL"
        nopasswd: yes
        cmd: "ALL"

# 09 # SSH

# 10 # Dirs

common_dirs:
  - path: "/var/shared/backups"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0750"
    force: no
    follow: yes

# 11 # Environments

common_environments:
  - user: "root"
    variables:
      PATH: "${PATH}:${HOME}/.bin:${HOME}/bin"
      MOLECULE: "YES"
  - user: "molecule"
    variables:
      PATH: "${PATH}:${HOME}/.bin:${HOME}/bin"
      MOLECULE: "YES"

# 12 # Limits

common_limits:
  - domain: "*"
    limit_type: "soft"
    limit_item: "nofile"
    value: "65536"
    use_max: yes
  - domain: "*"
    limit_type: "hard"
    limit_item: "nofile"
    value: "65536"
    use_max: yes

# 13 # Sysctl

common_sysctl_file: "ansible-common.conf"
common_sysctl_keys:
  - name: "net.core.somaxconn"
    value: "65535"

# 14 # Sysfs

common_sysfs:
  - attribute: "sys/kernel/mm/transparent_hugepage/enabled"
    value: "madvise"
    type: "attribute"

# 15 # Tuned

common_tuned_enable: yes
common_tuned_profile_name: "molecule"
common_tuned_profile_config:
  - name: "main"
    params:
      - option: "summary"
        value: "Test"
      - option: "include"
        value: "throughput-performance"
  - name: "sysctl"
    params:
      - option: "vm.dirty_ratio"
        value: "30"
      - option: "vm.swappiness"
        value: "30"
  - name: "vm"
    params:
      - option: "transparent_hugepages"
        value: "never"

# 16 # Firewall

# 17 # SELinux

# 18 # AIDE

common_aide_enable: yes
common_aide_config_file: "{{ inventory_dir }}/.files/{{ ansible_os_family | lower }}.aide.conf"

# 19 # Atop

common_atop_enable: yes
common_atop_options:
  - option: "LOGINTERVAL"
    value: "5"
  - option: "LOGGENERATIONS"
    value: "7"

# 20 # Auditd

common_auditd_enable: yes

# 21 # Chrony

common_chrony_enable: yes

# 22 # Cron

common_cron_environments:
  - user: "molecule"
    vars:
      - name: "MAILTO"
        value: "molecule@exmaple.com"

# 23 # Logwatch

common_logwatch_enable: yes
common_logwatch_mail_to: "molecule@example.com"
common_logwatch_mail_from: "logwatch@{{ inventory_hostname }}"
common_logwatch_hostname: "{{ inventory_hostname }}"

# 24 # NSCD

common_nscd_enable: yes

# 25 # Rootkit Hunter

common_rkhunter_enable: yes

# 26 # Smartmontools

# 27 # SSHD

common_sshd_options:
  - option: "pub_key_authentication"
    value: "yes"
  - option: "password_authentication"
    value: "no"
  - option: "gss_api_authentication"
    value: "no"
  - option: "kerberos_authentication"
    value: "no"
  - option: "permit_root_login"
    value: "no"

# 28 # ZSH

common_zsh:
  - user: "root"
  - user: "molecule"
