# code: language=ansible
---

- name: "Common | Hosts | Create /etc/hosts file"
  ansible.builtin.template:
    src: "hosts/hosts.j2"
    dest: "/etc/hosts"
    owner: "root"
    group: "root"
    mode: "0644"
    backup: no
  become: yes
  tags:
    - common
    - common-hosts
