# code: language=ansible
---

- name: "Common | Repositories | Dnf / Yum | Manager"
  community.general.ini_file:
    path: "/etc/dnf/dnf.conf"
    section: "{{ item.section | default('main') }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    no_extra_spaces: true
    mode: '0644'
  with_items: "{{ common_repositories_manager }}"
  when:
    - common_repositories_manager | is_ne_list_dicts
  become: yes
  become_user: "{{ ansible_become_user }}"
  tags:
    - common
    - common-repositories
    - common-repositories-manager

- name: "Common | Repositories | Dnf / Yum | GPG Keys"
  ansible.builtin.rpm_key:
    key: "{{ item.key }}"
    state: present
  with_items: "{{ common_repositories_add }}"
  when:
    - common_repositories_add | is_ne_list_dicts
    - item.key is defined
  become: yes
  become_user: "{{ ansible_become_user }}"
  tags:
    - common
    - common-repositories
    - common-repositories-gpg-keys

- name: "Common | Repositories | Dnf / Yum | Add repository"
  ansible.builtin.template:
    src: "repositories/dnf.repo.j2"
    dest: "/etc/yum.repos.d/{{ item.name }}.repo"
    owner: "root"
    group: "root"
    mode: "0644"
    backup: no
  with_items: "{{ common_repositories_add }}"
  when:
    - common_repositories_add | is_ne_list_dicts
  notify:
    - Update dnf cache
  become: yes
  become_user: "{{ ansible_become_user }}"
  tags:
    - common
    - common-repositories
    - common-repositories-add

- name: "Common | Repositories | Dnf / Yum | Get Repositories List"
  scan_repositories:
  become: yes
  when:
    - common_repositories_enable | is_ne_list or
      common_repositories_disable | is_ne_list
  tags:
    - common
    - common-repositories
    - common-repositories-enable
    - common-repositories-disable

- name: "Common | Repositories | Dnf / Yum | Get Repositories List | Debug"
  ansible.builtin.debug:
    var: ansible_facts.repositories
    verbosity: 1

- name: "Common | Repositories | Dnf / Yum | Enable repository"
  community.general.ini_file:
    path: "/etc/yum.repos.d/{{ item.file }}"
    section: "{{ item.name }}"
    option: "enabled"
    value: "1"
    mode: '0644'
  with_items: "{{ ansible_facts.repositories }}"
  when:
    - common_repositories_enable | is_ne_list
    - item.name is defined
    - item.name in common_repositories_enable
    - not item.state
  notify:
    - Update dnf cache
  become: yes
  tags:
    - common
    - common-repositories
    - common-repositories-enable

- name: "Common | Repositories | Dnf / Yum | Disable repository"
  community.general.ini_file:
    path: "/etc/yum.repos.d/{{ item.file }}"
    section: "{{ item.name }}"
    option: "enabled"
    value: "0"
    mode: '0644'
  with_items: "{{ ansible_facts.repositories }}"
  when:
    - common_repositories_disable | is_ne_list
    - item.name is defined
    - item.name in common_repositories_disable
    - item.state
  notify:
    - Update dnf cache
  become: yes
  tags:
    - common
    - common-repositories
    - common-repositories-enable

- name: "Common | Repositories | Dnf | Flush handlers"
  ansible.builtin.meta: flush_handlers
  tags:
    - common
    - common-repositories
    - common-repositories-add
    - common-repositories-enable
    - common-repositories-disable
